---
# tasks file for aws

- name: Install epel-release
  yum:
    name: epel-release
    state: installed
    #notify: update aide
  tags:
    - install

- name: Install AWS CLI packages
  yum:
    name: '{{ aws_packages }}'
    state: installed
    #notify: update aide
  tags:
    - install

